global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using BepInEx;
global using BepInEx.Configuration;
global using BepInEx.Logging;
global using MonoMod.RuntimeDetour;
global using UnityEngine;
global using UnityEngine.SceneManagement;
global using Random = UnityEngine.Random;
global using KEEK.Trainer.Utils;